"""========== MLRSNet ==========="""
### ResNet50
python diva_main.py --dataset MLRSNet --log_online --project MLRSNet_Diva  --source_path "/media/jun/Intenso/Dataset" --save_path "/home/jun/Documents/CV4RS/Diva" --group MLRSNet_DiVA-R50-512 --tau 55 --gamma 0.2 --diva_alpha_ssl 0.3 --diva_alpha_shared 0.3 --diva_alpha_intra 0.3 --diva_rho_decorrelation 1500 1500 1500 --diva_features discriminative selfsimilarity shared intra  --evaltypes all --diva_moco_temperature 0.01  --diva_moco_n_key_batches 30 --n_epochs 350 --seed 0 --gpu 0 --samples_per_class 2 --loss margin --loss_ssl fast_moco --batch_mining distance --batch_mining_shared random_distance --batch_mining_intra intra_random --arch multifeature_resnet50 --embed_dim 128
### Inception-BN
python diva_main.py --dataset MLRSNet --log_online --project MLRSNet_Diva  --source_path  "/scratch/CV4RS/Dataset" --save_path "/home/jun/Documents/CV4RS/Diva" --group MLRSNet_DiVA-IBN-512 --gamma 0.3 --tau 70 --diva_alpha_ssl 0.1 --diva_alpha_shared 0.1 --diva_alpha_intra 0.1 --diva_rho_decorrelation 300 300 300 --diva_features discriminative selfsimilarity shared intra  --evaltypes all --diva_moco_temperature 0.01  --diva_moco_n_key_batches 30 --n_epochs 350 --seed 0 --gpu 0 --samples_per_class 2 --loss margin  --loss_ssl fast_moco --batch_mining distance --batch_mining_shared random_distance --batch_mining_intra intra_random --arch multifeature_bninception --embed_dim 128

"""========== BigEarthNet ==========="""
### ResNet50
python diva_main.py --dataset BigEarthNet --log_online --project BigEarthNet_Diva  --source_path "/scratch/CV4RS/Dataset" --save_path "/home/jun/Documents/CV4RS/Diva" --group BigEarthNet_DiVA-R50-512 --tau 55 --gamma 0.2 --diva_alpha_ssl 0.3 --diva_alpha_shared 0.3 --diva_alpha_intra 0.3 --diva_rho_decorrelation 1500 1500 1500 --diva_features discriminative selfsimilarity shared intra  --evaltypes all --diva_moco_temperature 0.01  --diva_moco_n_key_batches 30 --n_epochs 350 --seed 0 --gpu 0 --samples_per_class 2 --loss margin  --loss_ssl fast_moco --batch_mining distance --batch_mining_shared random_distance --batch_mining_intra intra_random --arch multifeature_resnet50 --embed_dim 128
### Inception-BN
python diva_main.py --dataset BigEarthNet --log_online --project BigEarthNet_Diva  --source_path "/scratch/CV4RS/Dataset" --save_path "/home/jun/Documents/CV4RS/Diva" --group BigEarthNet_DiVA-IBN-512 --gamma 0.3 --tau 70 --diva_alpha_ssl 0.1 --diva_alpha_shared 0.1 --diva_alpha_intra 0.1 --diva_rho_decorrelation 300 300 300 --diva_features discriminative selfsimilarity shared intra --evaltypes all --diva_moco_temperature 0.01  --diva_moco_n_key_batches 30 --n_epochs 350 --seed 0 --gpu 0 --samples_per_class 2 --loss margin  --loss_ssl fast_moco --batch_mining distance --batch_mining_shared random_distance --batch_mining_intra intra_random --arch multifeature_bninception --embed_dim 128


"""==== INCLUDE DIFFERENT SELF-SUPERVISION APPROACHES ===="""
### e.g. Deep Clustering
python diva_main.py --source_path $datapath --log_online --project DiVA_Experiments --diva_rho_decorrelation 500 --diva_features discriminative dc --evaltypes all --diva_dc_update_f 2 --diva_dc_ncluster 300 --n_epochs 200 --seed 0 --gpu $gpu --bs 104 --samples_per_class 2 --loss margin --batch_mining distance --arch bninception_normalize --embed_dim 256
